### ISSUE TITLE
spider 无法部署

### ISSUE THREAD

**Issue by wo10378931** [tikazyq/crawlab#83]
爬虫部署的时候报一下错误：
```
/usr/local/lib/python3.6/dist-packages/pymongo/topology.py:149: UserWarning: MongoClient opened before fork. Create MongoClient only after forking. See PyMongo's documentation for details: http://api.mongodb.org/python/current/faq.html#is-pymongo-fork-safe
  "MongoClient opened before fork. Create MongoClient only "
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/util.py", line 319, in _exit_function
    p.join()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 122, in join
    assert self._parent_pid == os.getpid(), 'can only join a child process'
AssertionError: can only join a child process
```

不是很明白。

**Comment by tikazyq** [comment]
将在新版本v0.3.0解决，即将发布

**Comment by wo10378931** [comment]
感谢 ~  另外，安装文档的三个文档都是404了。
