### ISSUE TITLE
爬虫运行时报错

### ISSUE THREAD

**Issue by NameJaho** [tikazyq/crawlab#9]
[2019-04-01 11:40:33,715: ERROR/MainProcess] Task handler raised error: ValueError('not enough values to unpack (expected 3, got 0)',)
Traceback (most recent call last):
  File "C:\Users\xiaojiahao\Envs\jaho\lib\site-packages\billiard\pool.py", line 358, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
  File "C:\Users\xiaojiahao\Envs\jaho\lib\site-packages\celery\app\trace.py", line 537, in _fast_trace_task
    tasks, accept, hostname = _loc
ValueError: not enough values to unpack (expected 3, got 0)

**Comment by tikazyq** [comment]
解决方法: https://blog.csdn.net/qq_30242609/article/details/79047660

需要在windows上安装eventlet

`pip install eventlet`

**Comment by NameJaho** [comment]
> 解决方法: https://blog.csdn.net/qq_30242609/article/details/79047660
> 
> 需要在windows上安装eventlet
> 
> `pip install eventlet`

eventlet已经存在 还是出现同样的问题

**Comment by tikazyq** [comment]
是sys.platform判断的bug，已经修复
